#!/bin/sh

######################################
#
# Dependencies
#
######################################

# shellcheck disable=SC2164
SCRIPT_ABSOLUTE_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# shellcheck disable=SC2039
source "$SCRIPT_ABSOLUTE_PATH/.src/config"

######################################
#
# Start Docker Containers
#
######################################

cd "${SCRIPT_ABSOLUTE_PATH}" && cd ..

cd "${PATH_SERVICE_API}" && lnav laravel/storage/logs/laravel.log

docker ps