#!/bin/sh

######################################
#
# Dependencies
#
######################################

# shellcheck disable=SC2164
SCRIPT_ABSOLUTE_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# shellcheck disable=SC2039
source "$SCRIPT_ABSOLUTE_PATH/.src/config"

######################################
#
# Start Docker Containers
# When the containers are started, Docker will execute the entrypoint files in each container
#
######################################

cd "${SCRIPT_ABSOLUTE_PATH}" && cd ..

cd "${PATH_SERVICE_API}" && docker-compose up -d
cd "${PATH_SERVICE_GUI}" && docker-compose up -d
cd "${PATH_SERVICE_ASSETS}" && docker-compose up -d
cd "${PATH_SERVICE_ANALYTICS}" && docker-compose up -d

docker ps

# shellcheck disable=SC2028
echo "\nLimitless GUI (VueJS, JavaScript): localhost:8082"
# shellcheck disable=SC2028
echo "Limitless API (Laravel, PHP): localhost:8083"
# shellcheck disable=SC2028
echo "Limitless ANALYTICS (Python): localhost:8081\n"