#!/bin/sh

# shellcheck disable=SC2164
SCRIPT_ABSOLUTE_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

######################################
#
# Step 0: Load Dependencies
#
######################################

# shellcheck disable=SC2039
source "$SCRIPT_ABSOLUTE_PATH/.src/config"

# shellcheck disable=SC2039
source "$SCRIPT_ABSOLUTE_PATH/.src/helpers"

######################################
#
# Step 1: Recursive git status
#
######################################

echo "\n${YELLOW}Git Status: API${NC}\n"
cd "${PATH_SERVICE_API}" && git status

echo "\n${YELLOW}Git Status: GUI${NC}\n"
cd "${PATH_SERVICE_GUI}" && git status

echo "\n${YELLOW}Git Status: ASSETS${NC}\n"
cd "${PATH_SERVICE_ASSETS}" && git status

echo "\n${YELLOW}Git Status: ANALYTICS${NC}\n"
cd "${PATH_SERVICE_ANALYTICS}" && git status