#!/bin/sh
################################################################
################################################################
####
#### Configuration File
#### This file serves with the installation configuration
####
################################################################
################################################################

# shellcheck disable=SC2164
CONFIG_FILE_ABSOLUTE_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

################################
#### Coonfiguration Settings
################################

CONFIG_PARENT_FOLDER="src"
CONFIG_GUI_FOLDER="limitless-gui"
CONFIG_API_FOLDER="limitless-api"
CONFIG_ANALYTICS_FOLDER="limitless-analytics"

################################
#### Installation Paths
################################

cd "${CONFIG_FILE_ABSOLUTE_PATH}" && cd ..

INSTALLATION_PATH="$(pwd)/${CONFIG_PARENT_FOLDER}"

PATH_SERVICE_GUI="${INSTALLATION_PATH}/${CONFIG_GUI_FOLDER}"
PATH_SERVICE_API="${INSTALLATION_PATH}/${CONFIG_API_FOLDER}"
PATH_SERVICE_ANALYTICS="${INSTALLATION_PATH}/${CONFIG_ANALYTICS_FOLDER}"