#!/bin/sh
trap "exit 1" TERM
export TOP_PID=$$

abortIfProjectFoldersExist() {
  for folderName in "$@"; do
    if [ -d "$folderName" ]; then
      echo "\nFolder is not empty: $folderName"
      echo "Delete the contents of the 'src' directory and restart installation."
      exit;
    fi
  done
}